# Generated by Django 3.0.5 on 2020-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
